contents:
  repositories:
    - https://packages.wolfi.dev/os
    - ./packages
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - ./local-melange.rsa.pub
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - prometheus-custom
    - tzdata

accounts:
  groups:
    - groupname: prometheus
      gid: 9090
  users:
    - username: prometheus
      uid: 9090
      gid: 9090
  run-as: 9090

paths:
  # Katalog dla Vaulta (tu wyląduje Twój sekret)
  - path: /prometheus
    type: directory
    permissions: 0755
    uid: 9090
    gid: 9090
    recursive: true
  
  # Katalog dla bibliotek konsoli (zgodnie z deploymentem OKD)
  - path: /etc/prometheus
    type: directory
    permissions: 0755
    uid: 9090
    gid: 9090
    recursive: true

entrypoint:
  # TYLKO BINARKA. Flagi przyjdą z OKD (args).
  command: /usr/bin/prometheus

archs:
  - amd64